##########################################################################
##									##	
##      SCHEDULE FILE							##
##									##
##	Cron expression string						##
##									##
##  *    *    *    *    *    *						##
##  -    -    -    -    -    -						##
##  |    |    |    |    |    |						##
##  |    |    |    |    |    + year [optional]				##
##  |    |    |    |    +----- day of week (0 - 7) (Sunday=0 or 7)	##
##  |    |    |    +---------- month (1 - 12)				##
##  |    |    +--------------- day of month (1 - 31)			##
##  |    +-------------------- hour (0 - 23)				##
##  +------------------------- min (0 - 59)				##
##									##
##	Schedule job example						##
##									##
## job_name:								##
##     instance_id: XXXXXXXX						##
##     start: "00 09 * * *"						##
##     shutdown: "00 18 * * *"						##
##									##
##########################################################################
---

##test001_job:
##    instance_id: i-941d3973
##    start: "30 8 * * *"
##    shutdown: "30 17 * * *"
    
